//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	DOOM main program (D_DoomMain) and game loop (D_DoomLoopTick),
//	plus functions to determine game mode (shareware, registered),
//	parse command line parameters, configure game parameters (turbo),
//	and call the startup functions.
//
//-----------------------------------------------------------------------------

static const char rcsid[] = "$Id: d_main.c,v 1.8 1997/02/03 22:45:09 b1 Exp $";

#define BGCOLOR 7
#define FGCOLOR 8

#ifdef NORMALUNIX
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#endif

#include "doomdef.h"
#include "doomstat.h"

#include "dstrings.h"
#include "sounds.h"

#include "s_sound.h"
#include "v_video.h"
#include "w_wad.h"
#include "z_zone.h"

#include "f_finale.h"
#include "f_wipe.h"

#include "m_argv.h"
#include "m_menu.h"
#include "m_misc.h"

#include "i_sound.h"
#include "i_system.h"
#include "i_video.h"

#include "g_game.h"

#include "am_map.h"
#include "hu_stuff.h"
#include "st_stuff.h"
#include "wi_stuff.h"

#include "p_setup.h"
#include "r_local.h"

#include "d_main.h"

// @REMOVAL
// Upstream's forward declaration and definition of `D_DoomLoop` (the
// `while(1)` console game loop) are gone. The browser host owns the event
// loop and drives the engine via `D_DoomLoopTick` (defined below) one frame
// at a time, so a blocking in-engine loop cannot exist.

char *wadfiles[MAXWADFILES];

// @REMOVAL
// `boolean devparm` (the `-devparm` dev-mode flag) is gone. wasmdoom has no
// developer console mode; the F1 screenshot shortcut, dev IWAD paths
// (`-shdev`/`-regdev`/`-comdev`), the dev-only deathmatch-spawn cheat, and
// the dev banner were all removed alongside it.
boolean nomonsters;  // checkparm of -nomonsters
boolean respawnparm; // checkparm of -respawn
boolean fastparm;    // checkparm of -fast

boolean drone;

boolean singletics = false; // debug flag to cancel adaptiveness

// extern int soundVolume;
// extern  int	sfxVolume;
// extern  int	musicVolume;

extern boolean inhelpscreens;

skill_t startskill;
int startepisode;
int startmap;
boolean autostart;

FILE *debugfile;

boolean advancedemo;

char wadfile[1024];     // primary wad file
char mapdir[1024];      // directory of development maps
char basedefault[1024]; // default file

void D_CheckNetGame(void);
void D_ProcessEvents(void);
void G_BuildTiccmd(ticcmd_t *cmd);
void D_DoAdvanceDemo(void);

//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t events[MAXEVENTS];
int eventhead;
int eventtail;

//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent(event_t *ev) {
  events[eventhead] = *ev;
  eventhead = (++eventhead) & (MAXEVENTS - 1);
}

//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents(void) {
  event_t *ev;

  // IF STORE DEMO, DO NOT ACCEPT INPUT
  if ((gamemode == commercial) && (W_CheckNumForName("map01") < 0))
    return;

  for (; eventtail != eventhead; eventtail = (++eventtail) & (MAXEVENTS - 1)) {
    ev = &events[eventtail];
    if (M_Responder(ev))
      continue; // menu ate the event
    G_Responder(ev);
  }
}

//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t wipegamestate = GS_DEMOSCREEN;
extern boolean setsizeneeded;
extern int showMessages;
void R_ExecuteSetViewSize(void);

// A wipe spans multiple ticks; these persist its progress between frames.
static boolean wipe_in_progress = false;
static int wipe_starttime;

void D_Display(void) {
  static boolean viewactivestate = false;
  static boolean menuactivestate = false;
  static boolean inhelpscreensstate = false;
  static boolean fullscreen = false;
  static gamestate_t oldgamestate = -1;
  static int borderdrawcount;
  int nowtime;
  int tics;
  int y;
  boolean done;
  boolean wipe;
  boolean redrawsbar;

  if (nodrawers)
    return; // for comparative timing / profiling

  // A wipe is mid-animation: advance it, present frame, then yield.
  // We must skip the normal render path below, which would overwrite
  // screens[0] (the wipe's composite buffer).
  if (wipe_in_progress) {
    nowtime = I_GetTime();
    tics = nowtime - wipe_starttime;
    if (tics <= 0) {
      return; // <1 tic elapsed this frame; canvas keeps last wipe frame
    }
    wipe_starttime = nowtime;
    done = wipe_ScreenWipe(wipe_Melt, 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
    I_UpdateNoBlit();
    M_Drawer();       // menu drawn on top of the wipe
    I_FinishUpdate(); // single page flip / blit this frame
    if (done) {
      wipe_in_progress = false;
    }
    return;
  }

  redrawsbar = false;

  // change the view size if needed
  if (setsizeneeded) {
    R_ExecuteSetViewSize();
    oldgamestate = -1; // force background redraw
    borderdrawcount = 3;
  }

  // save the current screen if about to wipe
  if (gamestate != wipegamestate) {
    wipe = true;
    wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
  } else
    wipe = false;

  if (gamestate == GS_LEVEL && gametic)
    HU_Erase();

  // do buffered drawing
  switch (gamestate) {
  case GS_LEVEL:
    if (!gametic)
      break;
    if (automapactive)
      AM_Drawer();
    if (wipe || (viewheight != 200 && fullscreen))
      redrawsbar = true;
    if (inhelpscreensstate && !inhelpscreens)
      redrawsbar = true; // just put away the help screen
    ST_Drawer(viewheight == 200, redrawsbar);
    fullscreen = viewheight == 200;
    break;

  case GS_INTERMISSION:
    WI_Drawer();
    break;

  case GS_FINALE:
    F_Drawer();
    break;

  case GS_DEMOSCREEN:
    D_PageDrawer();
    break;
  }

  // draw buffered stuff to screen
  I_UpdateNoBlit();

  // draw the view directly
  if (gamestate == GS_LEVEL && !automapactive && gametic)
    R_RenderPlayerView(&players[displayplayer]);

  if (gamestate == GS_LEVEL && gametic)
    HU_Drawer();

  // clean up border stuff
  if (gamestate != oldgamestate && gamestate != GS_LEVEL)
    I_SetPalette(W_CacheLumpName("PLAYPAL", PU_CACHE));

  // see if the border needs to be initially drawn
  if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL) {
    viewactivestate = false; // view was not active
    R_FillBackScreen();      // draw the pattern into the back screen
  }

  // see if the border needs to be updated to the screen
  if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320) {
    if (menuactive || menuactivestate || !viewactivestate)
      borderdrawcount = 3;
    if (borderdrawcount) {
      R_DrawViewBorder(); // erase old menu stuff
      borderdrawcount--;
    }
  }

  menuactivestate = menuactive;
  viewactivestate = viewactive;
  inhelpscreensstate = inhelpscreens;
  oldgamestate = wipegamestate = gamestate;

  // draw pause pic
  if (paused) {
    if (automapactive)
      y = 4;
    else
      y = viewwindowy + 4;
    V_DrawPatchDirect(viewwindowx + (scaledviewwidth - 68) / 2, y, 0,
                      W_CacheLumpName("M_PAUSE", PU_CACHE));
  }

  // menus go directly to the screen
  M_Drawer();  // menu is drawn even on top of everything
  NetUpdate(); // send out any new accumulation

  // normal update
  if (!wipe) {
    I_FinishUpdate(); // page flip or blit buffer
    return;
  }

  // wipe update -- begin a non-blocking, per-tick wipe; the first wipe frame is
  // presented on the next D_DoomLoopTick via the wipe_in_progress branch above.
  wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
  wipe_starttime = I_GetTime() - 1; // -1 so the next tick advances >=1 melt tic
  wipe_in_progress = true;
}

// @ADDITION
// Runs a single iteration of the DOOM game loop: input, ticking, display and
// sound. Extracted from D_DoomLoop's while(1) so a host that owns the event
// loop (e.g. the WebAssembly browser host) can advance the game one frame at
// a time by calling this directly.
void D_DoomLoopTick(void) {
  // frame syncronous IO operations
  I_StartFrame();

  // Freeze the simulation while a screen wipe animates rather than have
  // `D_Display` be a blocking call.
  if (!wipe_in_progress) {
    // process one or more tics
    if (singletics) {
      I_StartTic();
      D_ProcessEvents();
      G_BuildTiccmd(&netcmds[consoleplayer][maketic % BACKUPTICS]);
      if (advancedemo)
        D_DoAdvanceDemo();
      M_Ticker();
      G_Ticker();
      gametic++;
      maketic++;
    } else {
      TryRunTics(); // will run at least one tic
    }
  }

  S_UpdateSounds(players[consoleplayer].mo); // move positional sounds

  // Update display, next frame, with current state.
  D_Display();

#ifndef SNDSERV
  // Sound mixing for the buffer is snychronous.
  I_UpdateSound();
#endif
  // Synchronous sound output is explicitly called.
#ifndef SNDINTR
  // Update sound output.
  I_SubmitSound();
#endif
}

//
//  DEMO LOOP
//
int demosequence;
int pagetic;
char *pagename;

//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker(void) {
  if (--pagetic < 0)
    D_AdvanceDemo();
}

//
// D_PageDrawer
//
void D_PageDrawer(void) {
  V_DrawPatch(0, 0, 0, W_CacheLumpName(pagename, PU_CACHE));
}

//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo(void) { advancedemo = true; }

//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
void D_DoAdvanceDemo(void) {
  players[consoleplayer].playerstate = PST_LIVE; // not reborn
  advancedemo = false;
  usergame = false; // no save / end game here
  paused = false;
  gameaction = ga_nothing;

  if (gamemode == retail)
    demosequence = (demosequence + 1) % 7;
  else
    demosequence = (demosequence + 1) % 6;

  switch (demosequence) {
  case 0:
    if (gamemode == commercial)
      pagetic = 35 * 11;
    else
      pagetic = 170;
    gamestate = GS_DEMOSCREEN;
    pagename = "TITLEPIC";
    if (gamemode == commercial)
      S_StartMusic(mus_dm2ttl);
    else
      S_StartMusic(mus_intro);
    break;
  case 1:
    G_DeferedPlayDemo("demo1");
    break;
  case 2:
    pagetic = 200;
    gamestate = GS_DEMOSCREEN;
    pagename = "CREDIT";
    break;
  case 3:
    G_DeferedPlayDemo("demo2");
    break;
  case 4:
    gamestate = GS_DEMOSCREEN;
    if (gamemode == commercial) {
      pagetic = 35 * 11;
      pagename = "TITLEPIC";
      S_StartMusic(mus_dm2ttl);
    } else {
      pagetic = 200;

      if (gamemode == retail)
        pagename = "CREDIT";
      else
        pagename = "HELP2";
    }
    break;
  case 5:
    G_DeferedPlayDemo("demo3");
    break;
    // THE DEFINITIVE DOOM Special Edition demo
  case 6:
    G_DeferedPlayDemo("demo4");
    break;
  }
}

//
// D_StartTitle
//
void D_StartTitle(void) {
  gameaction = ga_nothing;
  demosequence = -1;
  D_AdvanceDemo();
}

//      print title for every printed line
char title[128];

//
// D_AddFile
//
void D_AddFile(char *file) {
  int numwadfiles;
  char *newfile;

  for (numwadfiles = 0; wadfiles[numwadfiles]; numwadfiles++)
    ;

  newfile = malloc(strlen(file) + 1);
  strcpy(newfile, file);

  wadfiles[numwadfiles] = newfile;
}

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//

// @EDIT IdentifyVersion
// Body rewritten: the host stages the IWAD into linear memory and declares its
// gamemode (via wasmdoom_init), so there's no filesystem probing of IWAD
// filenames anymore. We only take the staged gamemode and set up the
// config-file path. Upstream's $DOOMWADDIR probing, the -shdev/-regdev/-comdev
// developer paths, the French-edition special-case, and the Freedoom fallback
// chain are all gone.
void IdentifyVersion(void) {
  char *home;

  gamemode = indetermined;

  int p = M_CheckParm("-mode");
  if (p && p < myargc - 1) {
    if (strcmp(myargv[p + 1], "shareware") == 0) {
      gamemode = shareware;
    } else if (strcmp(myargv[p + 1], "registered") == 0) {
      gamemode = registered;
    } else if (strcmp(myargv[p + 1], "commercial") == 0) {
      gamemode = commercial;
    } else if (strcmp(myargv[p + 1], "retail") == 0) {
      gamemode = retail;
    }
  }

  if (gamemode == indetermined) {
    printf("Game mode indeterminate.\n");
  }

  home = getenv("HOME");
  if (!home) {
    home = "/";
  }
  sprintf(basedefault, "%s/.doomrc", home);
}

//
// Find a Response File
//
void FindResponseFile(void) {
  int i;
#define MAXARGVS 100

  for (i = 1; i < myargc; i++)
    if (myargv[i][0] == '@') {
      FILE *handle;
      int size;
      int k;
      int index;
      int indexinfile;
      char *infile;
      char *file;
      char *moreargs[20];
      char *firstargv;

      // READ THE RESPONSE FILE INTO MEMORY
      handle = fopen(&myargv[i][1], "rb");
      if (!handle) {
        printf("\nNo such response file!");
        exit(1);
      }
      printf("Found response file %s!\n", &myargv[i][1]);
      fseek(handle, 0, SEEK_END);
      size = ftell(handle);
      fseek(handle, 0, SEEK_SET);
      file = malloc(size);
      fread(file, size, 1, handle);
      fclose(handle);

      // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
      for (index = 0, k = i + 1; k < myargc; k++)
        moreargs[index++] = myargv[k];

      firstargv = myargv[0];
      myargv = malloc(sizeof(char *) * MAXARGVS);
      memset(myargv, 0, sizeof(char *) * MAXARGVS);
      myargv[0] = firstargv;

      infile = file;
      indexinfile = k = 0;
      indexinfile++; // SKIP PAST ARGV[0] (KEEP IT)
      do {
        myargv[indexinfile++] = infile + k;
        while (k < size &&
               ((*(infile + k) >= ' ' + 1) && (*(infile + k) <= 'z')))
          k++;
        *(infile + k) = 0;
        while (k < size && ((*(infile + k) <= ' ') || (*(infile + k) > 'z')))
          k++;
      } while (k < size);

      for (k = 0; k < index; k++)
        myargv[indexinfile++] = moreargs[k];
      myargc = indexinfile;

      // DISPLAY ARGS
      printf("%d command-line args:\n", myargc);
      for (k = 1; k < myargc; k++)
        printf("%s\n", myargv[k]);

      break;
    }
}

//
// D_DoomMain
//
// @REMOVAL src/i_main.c
// The upstream `i_main.c` (which defined `main(argc, argv)` and called
// `D_DoomMain`) was deleted. The WebAssembly host calls `D_DoomMain` directly
// through the wasmdoom exports in `src/wasmdoom.c`; there is no C-level
// `main` entry point and the host populates `myargc`/`myargv`.
//
// @REMOVAL D_DoomMain CLI handling
// Several upstream command-line blocks have been dropped from this function:
//   - `-devparm` / `-altdeath` / `-deathmatch`  (no dev mode, no CLI
//   deathmatch)
//   - `-cdrom`                                  (no $HOME, no c:\doomdata)
//   - `-wart` / `-file` / `-playdemo` / `-timedemo`
//                                               (no filesystem PWAD/demo load)
//   - `-timer` / `-avg`                         (no deathmatch round timers)
//   - `-statcopy`                               (no external stats driver)
//   - `-record` / `-loadgame`                   (no record; saves go through
//                                                the host I_SaveGame hook, not
//                                                a startup-time filename)
//   - trailing `D_DoomLoop()` calls             (host owns the loop and pumps
//                                                `D_DoomLoopTick` itself)
// What remains is the engine-init pipeline plus a host-driven
// `G_InitNew` / `D_StartTitle` branch at the bottom.
void D_DoomMain(void) {
  int p;
  char file[256];

  FindResponseFile();

  IdentifyVersion();

  setbuf(stdout, NULL);
  modifiedgame = false;

  nomonsters = M_CheckParm("-nomonsters");
  respawnparm = M_CheckParm("-respawn");
  fastparm = M_CheckParm("-fast");

  switch (gamemode) {
  case retail:
    sprintf(title,
            "                         "
            "The Ultimate DOOM Startup v%i.%i"
            "                           ",
            VERSION / 100, VERSION % 100);
    break;
  case shareware:
    sprintf(title,
            "                            "
            "DOOM Shareware Startup v%i.%i"
            "                           ",
            VERSION / 100, VERSION % 100);
    break;
  case registered:
    sprintf(title,
            "                            "
            "DOOM Registered Startup v%i.%i"
            "                           ",
            VERSION / 100, VERSION % 100);
    break;
  case commercial:
    sprintf(title,
            "                         "
            "DOOM 2: Hell on Earth v%i.%i"
            "                           ",
            VERSION / 100, VERSION % 100);
    break;
    /*FIXME
           case pack_plut:
            sprintf (title,
                     "                   "
                     "DOOM 2: Plutonia Experiment v%i.%i"
                     "                           ",
                     VERSION/100,VERSION%100);
            break;
          case pack_tnt:
            sprintf (title,
                     "                     "
                     "DOOM 2: TNT - Evilution v%i.%i"
                     "                           ",
                     VERSION/100,VERSION%100);
            break;
    */
  default:
    sprintf(title,
            "                     "
            "Public DOOM - v%i.%i"
            "                           ",
            VERSION / 100, VERSION % 100);
    break;
  }

  printf("%s\n", title);

  // turbo option
  if ((p = M_CheckParm("-turbo"))) {
    int scale = 200;
    extern int forwardmove[2];
    extern int sidemove[2];

    if (p < myargc - 1)
      scale = atoi(myargv[p + 1]);
    if (scale < 10)
      scale = 10;
    if (scale > 400)
      scale = 400;
    printf("turbo scale: %i%%\n", scale);
    forwardmove[0] = forwardmove[0] * scale / 100;
    forwardmove[1] = forwardmove[1] * scale / 100;
    sidemove[0] = sidemove[0] * scale / 100;
    sidemove[1] = sidemove[1] * scale / 100;
  }

  // get skill / episode / map from parms
  startskill = sk_medium;
  startepisode = 1;
  startmap = 1;
  autostart = false;

  p = M_CheckParm("-skill");
  if (p && p < myargc - 1) {
    startskill = myargv[p + 1][0] - '1';
    autostart = true;
  }

  p = M_CheckParm("-episode");
  if (p && p < myargc - 1) {
    startepisode = myargv[p + 1][0] - '0';
    startmap = 1;
    autostart = true;
  }

  p = M_CheckParm("-warp");
  if (p && p < myargc - 1) {
    if (gamemode == commercial) {
      startmap = atoi(myargv[p + 1]);
    } else {
      startepisode = myargv[p + 1][0] - '0';
      startmap = myargv[p + 2][0] - '0';
    }
    autostart = true;
  }

  // init subsystems
  printf("V_Init: allocate screens.\n");
  V_Init();

  printf("M_LoadDefaults: Load system defaults.\n");
  M_LoadDefaults(); // load before initing other systems

  printf("Z_Init: Init zone memory allocation daemon. \n");
  Z_Init();

  printf("W_Init: Init WADfiles.\n");
  // @EDIT W_InitMultipleFiles -> W_InitFromMemory
  // The IWAD is staged in linear memory by the host (no filesystem). Any
  // PWADs in `wadfiles` are still loaded by name afterwards.
  W_InitFromMemory(wadfiles);

  // Check for -file in shareware
  if (modifiedgame) {
    // These are the lumps that will be checked in IWAD,
    // if any one is not present, execution will be aborted.
    char name[23][8] = {"e2m1",   "e2m2",   "e2m3",    "e2m4",   "e2m5",
                        "e2m6",   "e2m7",   "e2m8",    "e2m9",   "e3m1",
                        "e3m3",   "e3m3",   "e3m4",    "e3m5",   "e3m6",
                        "e3m7",   "e3m8",   "e3m9",    "dphoof", "bfgga0",
                        "heada1", "cybra1", "spida1d1"};
    int i;

    if (gamemode == shareware) {
      I_Error("\nYou cannot -file with the shareware "
              "version. Register!");
    }

    // Check for fake IWAD with right name,
    // but w/o all the lumps of the registered version.
    if (gamemode == registered) {
      for (i = 0; i < 23; i++) {
        if (W_CheckNumForName(name[i]) < 0) {
          I_Error("\nThis is not the registered version.");
        }
      }
    }
  }

  // Iff additonal PWAD files are used, print modified banner
  if (modifiedgame) {
    /*m*/ printf(
        "======================================================================"
        "=====\n"
        "ATTENTION:  This version of DOOM has been modified.  If you would "
        "like to\n"
        "get a copy of the original game, call 1-800-IDGAMES or see the readme "
        "file.\n"
        "        You will not receive technical support for modified games.\n"
        "                      press enter to continue\n"
        "======================================================================"
        "=====\n");
    getchar();
  }

  // Check and print which version is executed.
  switch (gamemode) {
  case shareware:
  case indetermined:
    printf("==================================================================="
           "========\n"
           "                                Shareware!\n"
           "==================================================================="
           "========\n");
    break;
  case registered:
  case retail:
  case commercial:
    printf("==================================================================="
           "========\n"
           "                 Commercial product - do not distribute!\n"
           "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
           "==================================================================="
           "========\n");
    break;

  default:
    // Ouch.
    break;
  }

  printf("M_Init: Init miscellaneous info.\n");
  M_Init();

  printf("R_Init: Init DOOM refresh daemon - ");
  R_Init();

  printf("\nP_Init: Init Playloop state.\n");
  P_Init();

  printf("I_Init: Setting up machine state.\n");
  I_Init();

  printf("D_CheckNetGame: Checking network game status.\n");
  D_CheckNetGame();

  printf("S_Init: Setting up sound.\n");
  S_Init(snd_SfxVolume /* *8 */, snd_MusicVolume /* *8*/);

  printf("HU_Init: Setting up heads up display.\n");
  HU_Init();

  printf("ST_Init: Init status bar.\n");
  ST_Init();

  if (autostart || netgame) {
    G_InitNew(startskill, startepisode, startmap);
  } else {
    D_StartTitle(); // start up intro loop
  }
}
